name: todolite
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0-285.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_riverpod: ^2.3.2
  flutter_scripts: ^0.0.3
  collection: ^1.17.1
  go_router: ^6.2.0
  riverpod_annotation: ^2.0.2
  riverpod: ^2.3.2
  shortid: ^0.1.2
  path_provider: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

  flutter_lints: ^2.0.1
  build_runner: ^2.4.1
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4

flutter:
  uses-material-design: true

flutter_scripts:
scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  watch: flutter pub run build_runner watch
  generate_icons: flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: true
  ios: true
  image_path: "./assets/todoLiteLogo/todoLiteLogo.jpeg"
